### ISSUE TITLE
On this page is messed up

### ISSUE THREAD

**Issue by BadLiveware** [sourcegraph/docs#141]
The RHS "On this page" ToC picks the wrong elements to list

e.g. https://sourcegraph.com/docs/batch_changes/references/batch_spec_yaml_reference

<img width="1022" alt="image" src="https://github.com/sourcegraph/docs/assets/10245011/5287df1f-c24f-4d82-85dd-a2e01749ecb5">

**Comment by MaedahBatool** [comment]
Hey @BadLiveware, thank you for reporting. The issue has been fixed. Let me know if you're still having issues at your end.
