### ISSUE TITLE
[Cody Ignore] Add docs explaining the Sourcegraph admin can configure the Cody Ignore policy

### ISSUE THREAD

**Issue by dominiccooney** [sourcegraph/docs#222]
When users invoke actions in IDEs that are disabled because of the Enterprise Cody Ignore policy, we need to link them to a page explaining how to change the policy.

- [PRD](https://docs.google.com/document/d/10tD8n-5py4XWQD9c7doJB7zIuxa7lwiOkpo2d5NLlnA/edit#heading=h.10vr0jxhrd1r)
- [RFC910](https://docs.google.com/document/d/1PMeJHvY0ia2nMewFvs4vrFcmDbRDw9kSyljil-K8Pt8/edit#heading=h.trqab8y0kufp)

**Comment by kalanchan** [comment]
@kalanchan "learn more" should link to proper docs

**Comment by kalanchan** [comment]
update:
Working with Maedah & Aravind to include more screenshots around Cody Ignore. Backend documentation is done, just need more UI screenshots

**Comment by dominiccooney** [comment]
Moving this to the current release. We link to this page: https://sourcegraph.com/docs/cody/capabilities/ignore-context

That page doesn't talk about "Context Filters" (the new name for the feature) and talks about the file-based Cody Ignore.

**Comment by kalanchan** [comment]
@dominiccooney woops sorry, I forgot to tag the PR but we've been working on docs [here](https://github.com/sourcegraph/docs/pull/326#pullrequestreview-2089006303)
