### ISSUE TITLE
Click to copy icon for code snippets

### ISSUE THREAD

**Issue by MaedahBatool** [sourcegraph/docs#310]
Right now our code snippets do not have any click-to-code icons. We want to add it.

**Comment by zahidalidev** [comment]
Here is the draft PR for your review review: 
https://github.com/sourcegraph/docs/pull/330#issue-2301251963

**Comment by MaedahBatool** [comment]
Left some feedback on the PR.

**Comment by zahidalidev** [comment]
@MaedahBatool I have fixed the issue and pushed the changes
