### ISSUE TITLE
Make a component for Tabs view

### ISSUE THREAD

**Issue by MaedahBatool** [sourcegraph/docs#311]
Create a component for Tabs that switch content accordingly. Make sure the URL changes accordingly and does not affect the path.

Example:

- https://docs.github.com/en/copilot/github-copilot-chat/copilot-chat-in-ides/using-github-copilot-chat-in-your-ide?tool=jetbrains
- https://vercel.com/docs/functions/quickstart#create-a-serverless-function
- https://mintlify.com/docs/content/components/tabs#tab-props

**Comment by zahidalidev** [comment]
Hi @MaedahBatool, I hope you are doing well. Can you share more details on this task? So I can start working on this today.

**Comment by MaedahBatool** [comment]
@zahidalidev added some details in description
