### ISSUE TITLE
Fix Table layout issue

### ISSUE THREAD

**Issue by MaedahBatool** [sourcegraph/docs#313]
We need fix table layout especially for tables that span across the page width. For example, the [table here](https://sourcegraph.com/docs/code-search/queries#filters-all-searches) overflows the container width. 

![Image](https://github.com/sourcegraph/docs/assets/12712988/d86620a2-88af-4114-8288-74cbf940fdc8)

Right now there is no separate Table component that we are using. So far we are only adding simple markdown tables. Maybe an exclusive React component for Table could help.

**Comment by zahidalidev** [comment]
Hi @MaedahBatool, I have completed this task as well.
