### ISSUE TITLE
Improve workflow for versions

### ISSUE THREAD

**Issue by MaedahBatool** [sourcegraph/docs#314]
We need to look into improving our versioned workflows since duplication of folders isn't working out. It is causing potential issues like our server functions are timing out.

![Image](https://github.com/sourcegraph/docs/assets/12712988/f14a9929-251e-41fc-8efd-7061c2efb82e)

Look into Sourcegraph docs versioning. Few inpos:

- Example websites and their repo links:
   - https://github.com/github/docs
   - https://docs.github.com/en/enterprise-cloud@latest (GitHub also uses versioning through dropdown)
   - https://github.com/elastic/docs
   - https://www.elastic.co/guide/en/elasticsearch/reference/current/index-templates.html (Elastic docs already use versioning)

- Docs generators shows how they tackle versioning in their frameworks:
   - https://docs.readme.com/main/docs/versions
   - https://mintlify.com/docs/settings/versioning
   - https://docusaurus.io/

From the code in their docs repo we can see how they are versioning their docs.

**Comment by MaedahBatool** [comment]
@zahidalidev adding you to the issue so we can track progress.

**Comment by zahidalidev** [comment]
Got it.
