### ISSUE TITLE
Add "Edit this page" link on docs site

### ISSUE THREAD

**Issue by MaedahBatool** [sourcegraph/docs#334]
We need to add an "Edit this page" icon on our docs to let people directly make small edits in our docs from GitHub since the docs repo is public. Sometimes back I started working on a PR which now has so many merge conflicts 🙈

See if you can make use of it and continue with it. However, it's a huge PR. https://github.com/sourcegraph/docs/pull/212

Precisely this is what the PR does:
- You can see two folders `docs-old` and `docs` along with a `ToC.tsx` file
- `docs-old` has all the regular docs folder entries with index.mdx files
- `docs` has all modified folder entries without index.mdx files since the way ToC works requires it

I can walk you through more once we meet 1:1

**Comment by MaedahBatool** [comment]
@zahidalidev this is what we need to ship next.

**Comment by zahidalidev** [comment]
@MaedahBatool I have completed this Ticket, please review this [PR](https://github.com/sourcegraph/docs/pull/352#issue-2315582900)

**Comment by zahidalidev** [comment]
@MaedahBatool These endpoints are not available in version 5.2. Should I push them after commenting them out in the same PR?

- /cody/core-concepts/enterprise-architecture
- /cody/core-concepts/token-limits
- /cody/capabilities/supported-models
- /code-search/types/symbol

**Comment by zahidalidev** [comment]
Hi @MaedahBatool ,

I have removed the endpoints as discussed and pushed the changes to the same PR.
