### ISSUE TITLE
Fix padding issue in code blocks

### ISSUE THREAD

**Issue by MaedahBatool** [sourcegraph/docs#359]
There is some weird padding in our codeblocks.

![Image](https://github.com/sourcegraph/docs/assets/12712988/41c2b1fa-009e-435f-8d2a-7b38898ab082)

![Image](https://github.com/sourcegraph/docs/assets/12712988/dce28f90-f6ee-443c-8998-2f294d4883ee)

**Comment by MaedahBatool** [comment]
Hey @zahidalidev looks fine to me only one thing can Js be JS?

**Comment by zahidalidev** [comment]
@MaedahBatool please review this [PR](https://github.com/sourcegraph/docs/pull/377#issue-2328241759) for this this task



![Image](https://github.com/sourcegraph/docs/assets/46484008/75d89d14-6f8a-482b-936f-cd568f7240f8)

**Comment by zahidalidev** [comment]
Hi @MaedahBatool here is another version of the header with the same shade of code block and grey bottom border.



![Image](https://github.com/sourcegraph/docs/assets/46484008/d93aefc8-111f-44fe-907c-a5d08703869c)

**Comment by zahidalidev** [comment]
@MaedahBatool I have pushed the changes for style modifications please review this [PR](https://github.com/sourcegraph/docs/pull/377#issue-2328241759)
