### ISSUE TITLE
Add Thumbnail Image when you share a docs link

### ISSUE THREAD

**Issue by MaedahBatool** [sourcegraph/docs#361]
Right now when you share a docs link no thumbnail appears. 

![Image](https://github.com/sourcegraph/docs/assets/12712988/71877196-175c-49b6-8adc-a78f965417ee)

Let add one something like this:

![Image](https://github.com/sourcegraph/docs/assets/12712988/476ce187-bebf-4fbc-88ee-98cb69fdba66)

**Comment by zahidalidev** [comment]
@MaedahBatool Can you share the image or any description that you want to add for this task?

**Comment by MaedahBatool** [comment]
@zahidalidev OG image that you can use.

![Image](https://github.com/sourcegraph/docs/assets/12712988/79a4ec8e-2254-4b55-b578-01a0c72211ae)
