### ISSUE TITLE
Add "Give us feedback" link to the TOC

### ISSUE THREAD

**Issue by MaedahBatool** [sourcegraph/docs#405]
We need to add a link in our TOC that asks people to drop any questions or feedback on our Community forum. It should link here: https://community.sourcegraph.com/

- Inspo

![Image](https://github.com/sourcegraph/docs/assets/12712988/654376a1-9108-4606-b258-0908eebc1e79)

**Comment by zahidalidev** [comment]
I have completed this task, and will push it after merging sitemap PR.

![Image](https://github.com/sourcegraph/docs/assets/46484008/69f7966f-aaa0-421c-a14d-4bf09bd9c113)
