### ISSUE TITLE
Creating hero sections

### ISSUE THREAD

**Issue by MaedahBatool** [sourcegraph/docs#526]

**Comment by zahidalidev** [comment]
@MaedahBatool I have completed this ticket, and created a hero section.


![Image](https://github.com/user-attachments/assets/73646eef-ada4-4209-9d10-7b1a8db15847)

**Comment by MaedahBatool** [comment]
@zahidalidev is the header not full width?

**Comment by zahidalidev** [comment]
Yes @MaedahBatool It's not at full width as it appears in Figma. Here are screenshots from both Figma and the project for comparison.

Here is the screenshot from the Figma design:
<img width="1680" alt="image" src="https://github.com/user-attachments/assets/7fc307a9-25ef-45a3-b047-ddb77cf3883d">

And here the latest screenshot for the changelog page:
<img width="1680" alt="image" src="https://github.com/user-attachments/assets/78ac6a65-3212-4d57-8755-cb49f0b39e56">
