### ISSUE TITLE
Integrate header/appbar, hero section and footer to changeloge page

### ISSUE THREAD

**Issue by MaedahBatool** [sourcegraph/docs#527]

**Comment by zahidalidev** [comment]
@MaedahBatool I have completed this ticket and integrated all sections, mentioned here.


![Image](https://github.com/user-attachments/assets/66e5fd9f-ee6b-4309-b849-b990b59e7330)



![Image](https://github.com/user-attachments/assets/8b3b8462-011c-4bbb-ab22-8edd01498f70)
