### ISSUE TITLE
Create the complete UI design according to Figma for changelog page

### ISSUE THREAD

**Issue by MaedahBatool** [sourcegraph/docs#530]

**Comment by zahidalidev** [comment]
@MaedahBatool I have completed this ticket and created a changelog page according to Figma design, here are the screenshots.



![Image](https://github.com/user-attachments/assets/784716c2-85b5-416b-8662-3bef5a77ac69)



![Image](https://github.com/user-attachments/assets/398902aa-c131-4996-8f71-97361e5f2e84)
